;textoutput：文本输出开关，打开会自动读取所有进入的菜单页面文本并输出到menu_text.txt，没用了已经
;logoutput：日志输出开关
;console：控制台窗口开关
;displaymode：显示模式：full只显示汉化，mix汉化+原文，off关闭汉化
;pageexport：页面快照文本导出开关，按P可以导出当前显示的菜单文本到page_dump.txt里
[TextOutput]
TextOutput=off
LogOutput=off
Console=off
DisplayMode=mix
PageExport=on